[custom]
;视频演示规则，因为教学原因添加的类型比较全面，实际应用应尽量删减，在达到自己目的的情况下做到最简化，否则会造成网络卡顿和延迟！！！！！
;视频演示规则，因为教学原因添加的类型比较全面，实际应用应尽量删减，在达到自己目的的情况下做到最简化，否则会造成网络卡顿和延迟！！！！！
;视频演示规则，因为教学原因添加的类型比较全面，实际应用应尽量删减，在达到自己目的的情况下做到最简化，否则会造成网络卡顿和延迟！！！！！
;视频演示规则，因为教学原因添加的类型比较全面，实际应用应尽量删减，在达到自己目的的情况下做到最简化，否则会造成网络卡顿和延迟！！！！！



;自定义规则集
ruleset=🎯 直连,https://raw.githubusercontent.com/lwj945/rules-template/refs/heads/main/Direct.list
ruleset=🗺️ 代理,https://raw.githubusercontent.com/lwj945/rules-template/refs/heads/main/ProxyLite.list
ruleset=🗺️ EXhentai,https://raw.githubusercontent.com/lwj945/rules-template/refs/heads/main/EXhentai.list
ruleset=🗺️ JP,https://raw.githubusercontent.com/lwj945/rules-template/refs/heads/main/JP.list
ruleset=🤖 AI,https://raw.githubusercontent.com/lwj945/rules-template/refs/heads/main/AI.list
ruleset=🗺️ JAVDB,https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/refs/heads/meta/geo/geosite/javdb.list
;公共规则集
ruleset=🎯 直连,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/LocalAreaNetwork.list
ruleset=🎯 直连,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/UnBan.list
ruleset=🛑 广告拦截,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/BanAD.list
ruleset=🍃 应用净化,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/BanProgramAD.list
;ruleset=🆎 AdBlock,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/BanEasyList.list
;ruleset=🆎 AdBlock,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/BanEasyListChina.list
;ruleset=🛡️ 隐私防护,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/BanEasyPrivacy.list
ruleset=📢 FCM,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/GoogleFCM/GoogleFCM.list
ruleset=🎯 直连,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/GoogleCN.list
ruleset=🎯 直连,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/SteamCN.list
ruleset=👨🏿‍💻 GitHub,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/GitHub/GitHub.list
ruleset=👨🏿‍💻 GitHub,clash-classic:https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/GitHub/GitHub.yaml
ruleset=🍀 Google,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Google/Google.list
ruleset=💧 Copilot,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Bing.list
ruleset=🐬 OneDrive,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/OneDrive/OneDrive.list
ruleset=🪟 Microsoft,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Microsoft.list
ruleset=🍎 Apple,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Apple.list
ruleset=📲 Telegram,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Telegram/Telegram.list
ruleset=♻️ Speedtest,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Speedtest/Speedtest.list
ruleset=📹 YouTube,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/YouTube.list
ruleset=🎮 游戏平台,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/Epic.list
ruleset=🎮 游戏平台,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/Origin.list
ruleset=🎮 游戏平台,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/Sony.list
ruleset=🎮 游戏平台,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/Steam.list
ruleset=🎮 游戏平台,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/Nintendo.list
ruleset=🎥 Netflix,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/Netflix.list
ruleset=🎵 TikTok,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/TikTok/TikTok.list
ruleset=🎞️ 国内媒体,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/ChinaMedia/ChinaMedia.list
ruleset=🌍 国外媒体,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ProxyMedia.list
ruleset=🗺️ 代理,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ProxyGFWlist.list
ruleset=🎯 直连,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ChinaDomain.list
ruleset=🎯 直连,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ChinaCompanyIp.list
ruleset=🎯 直连,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Download.list
ruleset=🎯 直连,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/China/China.list
ruleset=🎯 直连,[]GEOSITE,CN
ruleset=🗺️ 代理,[]GEOSITE,geolocation-!cn
ruleset=🎯 直连,[]GEOIP,CN,no-resolve
ruleset=🐟 漏网之鱼,[]FINAL



custom_proxy_group=🚀 默认节点组`select`[]🔯 香港故转节点组`[]🔯 日本故转节点组`[]🔯 新加坡故转节点组`[]🔯 美国故转节点组`[]♻️ 香港自动`[]♻️ 日本自动`[]♻️ 新加坡自动`[]🇭🇰 香港节点组`[]🇯🇵 日本节点组`[]🇺🇲 美国节点组`[]🕊️ 便宜节点组`[]🔏 私有节点组`[]DIRECT
custom_proxy_group=🗺️ 代理`select`[]🚀 默认节点组`[]🔯 香港故转节点组`[]🔯 日本故转节点组`[]🔯 新加坡故转节点组`[]🔯 美国故转节点组`[]🇭🇰 香港节点组`[]🇯🇵 日本节点组`[]🇺🇲 美国节点组`[]🕊️ 便宜节点组`[]🔏 私有节点组`[]DIRECT
custom_proxy_group=🗺️ EXhentai`select`[]🚀 默认节点组`[]🔯 香港故转节点组`[]🔯 美国故转节点组`[]🔏 私有节点组`[]DIRECT
custom_proxy_group=🗺️ JP`select`[]🚀 默认节点组`[]🔯 香港故转节点组`[]🔯 日本故转节点组`[]🔏 私有节点组`[]DIRECT
custom_proxy_group=📹 YouTube`select`[]🚀 默认节点组`[]🔯 香港故转节点组`[]🔯 日本故转节点组`[]🔯 美国故转节点组`[]🇭🇰 香港节点组`[]🇯🇵 日本节点组`[]🇺🇲 美国节点组`[]🕊️ 便宜节点组`[]🔏 私有节点组`[]DIRECT
custom_proxy_group=🤖 AI`select`[]🚀 默认节点组`[]🔯 香港故转节点组`[]🔯 美国故转节点组`[]🇭🇰 香港节点组`[]🇺🇲 美国节点组`[]🕊️ 便宜节点组`[]🔏 私有节点组`[]DIRECT
custom_proxy_group=💧 Copilot`select`[]🚀 默认节点组`[]🔯 香港故转节点组`[]🔯 日本故转节点组`[]🔯 美国故转节点组`[]🇭🇰 香港节点组`[]🇯🇵 日本节点组`[]🇺🇲 美国节点组`[]🕊️ 便宜节点组`[]🔏 私有节点组`[]DIRECT
custom_proxy_group=🐬 OneDrive`select`[]🚀 默认节点组`[]🔯 香港故转节点组`[]🔯 日本故转节点组`[]🔯 美国故转节点组`[]🇭🇰 香港节点组`[]🇯🇵 日本节点组`[]🇺🇲 美国节点组`[]🕊️ 便宜节点组`[]🔏 私有节点组`[]DIRECT
custom_proxy_group=🪟 Microsoft`select`[]🚀 默认节点组`[]🔯 香港故转节点组`[]🔯 日本故转节点组`[]🔯 美国故转节点组`[]🇭🇰 香港节点组`[]🇯🇵 日本节点组`[]🇺🇲 美国节点组`[]🕊️ 便宜节点组`[]🔏 私有节点组`[]DIRECT
custom_proxy_group=🍀 Google`select`[]🚀 默认节点组`[]🔯 香港故转节点组`[]🔯 日本故转节点组`[]🔯 美国故转节点组`[]🇭🇰 香港节点组`[]🇯🇵 日本节点组`[]🇺🇲 美国节点组`[]🕊️ 便宜节点组`[]🔏 私有节点组`[]DIRECT
custom_proxy_group=👨🏿‍💻 GitHub`select`[]🚀 默认节点组`[]🔯 香港故转节点组`[]🔯 日本故转节点组`[]🔯 美国故转节点组`[]🇭🇰 香港节点组`[]🇯🇵 日本节点组`[]🇺🇲 美国节点组`[]🕊️ 便宜节点组`[]🔏 私有节点组`[]DIRECT
custom_proxy_group=🍎 Apple`select`[]DIRECT`[]🇭🇰 香港节点组`[]🇯🇵 日本节点组`[]🇺🇲 美国节点组`[]🚀 默认节点组
custom_proxy_group=♻️ Speedtest`select`[]DIRECT`[]🇭🇰 香港节点组`[]🇯🇵 日本节点组`[]🇺🇲 美国节点组`[]🚀 默认节点组
custom_proxy_group=🎵 TikTok`select`[]🚀 默认节点组`[]🔯 香港故转节点组`[]🔯 日本故转节点组`[]🔯 美国故转节点组`[]🇭🇰 香港节点组`[]🇯🇵 日本节点组`[]🇺🇲 美国节点组`[]🕊️ 便宜节点组`[]🔏 私有节点组`[]DIRECT
custom_proxy_group=🎥 Netflix`select`[]🚀 默认节点组`[]🎥 奈飞节点组`[]🔯 香港故转节点组`[]🔯 日本故转节点组`[]🔯 美国故转节点组`[]🇭🇰 香港节点组`[]🇯🇵 日本节点组`[]🇺🇲 美国节点组`[]🕊️ 便宜节点组`[]🔏 私有节点组`[]DIRECT
custom_proxy_group=📲 Telegram`select`[]🚀 默认节点组`[]🔯 香港故转节点组`[]🔯 日本故转节点组`[]🔯 美国故转节点组`[]🇭🇰 香港节点组`[]🇯🇵 日本节点组`[]🇺🇲 美国节点组`[]🕊️ 便宜节点组`[]🔏 私有节点组`[]DIRECT
custom_proxy_group=📢 FCM`select`[]🚀 默认节点组`[]🔯 香港故转节点组`[]🔯 日本故转节点组`[]🔯 美国故转节点组`[]🇭🇰 香港节点组`[]🇯🇵 日本节点组`[]🇺🇲 美国节点组`[]🕊️ 便宜节点组`[]🔏 私有节点组`[]DIRECT
custom_proxy_group=🎮 游戏平台`select`[]DIRECT`[]🚀 默认节点组`[]🔯 香港故转节点组`[]🔯 日本故转节点组`[]🔯 美国故转节点组`[]🇭🇰 香港节点组`[]🇯🇵 日本节点组`[]🇺🇲 美国节点组`[]🕊️ 便宜节点组`[]🔏 私有节点组
custom_proxy_group=🌍 国外媒体`select`[]🚀 默认节点组`[]🔯 香港故转节点组`[]🔯 日本故转节点组`[]🔯 美国故转节点组`[]🇭🇰 香港节点组`[]🇯🇵 日本节点组`[]🇺🇲 美国节点组`[]🕊️ 便宜节点组`[]🔏 私有节点组`[]DIRECT
custom_proxy_group=🎞️ 国内媒体`select`[]DIRECT`[]🚀 默认节点组
custom_proxy_group=🎯 直连`select`[]DIRECT`[]🚀 默认节点组`[]🔏 私有节点组
custom_proxy_group=🛑 广告拦截`select`[]REJECT`[]DIRECT
custom_proxy_group=🍃 应用净化`select`[]REJECT`[]DIRECT
;custom_proxy_group=🆎 AdBlock`select`[]REJECT`[]DIRECT
;custom_proxy_group=🛡️ 隐私防护`select`[]REJECT`[]DIRECT
custom_proxy_group=🐟 漏网之鱼`select`[]DIRECT`[]🚀 默认节点组`[]🇭🇰 香港节点组`[]🇯🇵 日本节点组
custom_proxy_group=🗺️ JAVDB`select`[]DIRECT`[]🚀 默认节点组`[]🔯 JAVDB

;节点组
custom_proxy_group=🐸 手动切换节点组`select`.*
;custom_proxy_group=🏡 家宽节点组`select`(家宽|家庭)
custom_proxy_group=🔏 私有节点组`select`(私有|个人|私人|自建)
;custom_proxy_group=🛩️ 高速节点组`select`(?=.*(香港|hk|HK|日本|JP|jp|SG|新加坡|专线))(?!.*0\.[1-5]).*$
custom_proxy_group=🕊️ 便宜节点组`select`.*(0\.[1-5]).*
custom_proxy_group=🇭🇰 香港节点组`select`.*(香港|HK|Hong Kong|🇭🇰|HongKong)(?!.*0\.[1-5]).*
custom_proxy_group=🇯🇵 日本节点组`select`.*(日本|川日|东京|大阪|泉日|埼玉|沪日|深日|JP|Japan)(?!.*0\.[1-5]).*
;custom_proxy_group=🇸🇬 新加坡节点组`select`.*(新加坡|坡|狮城|SG|Singapore)(?!.*0\.[1-5]).*
custom_proxy_group=🇺🇲 美国节点组`select`.*(美|波特兰|达拉斯|俄勒冈|凤凰城|费利蒙|硅谷|拉斯维加斯|洛杉矶|圣何塞|圣克拉拉|西雅图|芝加哥|US|United States)(?!.*0\.[01-5]).*
;custom_proxy_group=🌐 其他地区节点组`select`^(?!.*(香港|HK|Hong Kong|🇭🇰|HongKong|日本|川日|东京|大阪|泉日|埼玉|沪日|深日|JP|Japan|新加坡|坡|狮城|SG|Singapore|美|波特兰|达拉斯|俄勒冈|凤凰城|费利蒙|硅谷|拉斯维加斯|洛杉矶|圣何塞|圣克拉拉|西雅图|芝加哥|US|United States)).*$
custom_proxy_group=🔯 香港故转节点组`fallback`^.*(香港|HK|Hong Kong|🇭🇰|HongKong)(?!.*0\.[1-5]).*$`http://www.gstatic.com/generate_204`300,10,50
custom_proxy_group=🔯 日本故转节点组`fallback`^.*(日本|川日|东京|大阪|泉日|埼玉|沪日|深日|JP|Japan)(?!.*0\.[1-5]).*$`http://www.gstatic.com/generate_204`300,10,50
custom_proxy_group=🔯 新加坡故转节点组`fallback`^.*(新加坡|坡|狮城|SG|Singapore)(?!.*0\.[1-5]).*$`http://www.gstatic.com/generate_204`300,10,50
custom_proxy_group=🔯 美国故转节点组`fallback`^.*(美|波特兰|达拉斯|俄勒冈|凤凰城|费利蒙|硅谷|拉斯维加斯|洛杉矶|圣何塞|圣克拉拉|西雅图|芝加哥|US|United States)(?!.*0\.[01-5]).*$`http://www.gstatic.com/generate_204`300,10,50
;custom_proxy_group=🍃 香港负载均衡节点组`load-balance`^.*(香港|HK|Hong Kong|🇭🇰|HongKong).*$`http://www.gstatic.com/generate_204`300,10,50
;custom_proxy_group=♻️ 自动选择节点组`url-test`.*`http://www.gstatic.com/generate_204`300,5,50
custom_proxy_group=🎥 奈飞节点组`select`(NF|奈飞|解锁|Netflix|NETFLIX|Media)
custom_proxy_group=🔯 JAVDB`select`^(?!.*(日本|川日|东京|大阪|泉日|埼玉|沪日|深日|JP|Japan|美|波特兰|达拉斯|俄勒冈|凤凰城|费利蒙|硅谷|拉斯维加斯|洛杉矶|圣何塞|圣克拉拉|西雅图|芝加哥|US|United States)).*$
custom_proxy_group=♻️ 香港自动`url-test`.*(港|HK|(?i)Hong).*$`http://www.gstatic.com/generate_204`300,5,50
custom_proxy_group=♻️ 日本自动`url-test`.*(日|JP|(?i)Japan).*$`http://www.gstatic.com/generate_204`300,5,50
custom_proxy_group=♻️ 新加坡自动`url-test`.*(新加坡|坡|狮城|SG|Singapore).*$`http://www.gstatic.com/generate_204`300,5,50
;启用自定义规则集

enable_rule_generator=true
overwrite_original_rules=true
enable_cache=false
cache_subscription=0
cache_config=0
cache_ruleset=0

